databases:
  - name: render_app
    databaseName: render_app_sexu
    user: render_app_sexu_user
    region: singapore

services:
  - type: web
    name: render_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

